/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Practical6.Q3;

import java.io.BufferedWriter;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.PrintWriter;

/**
 *
 * @author elliott
 */
public class BreadFactoryFrame extends javax.swing.JFrame {

        /**
         * Creates new form BreadFactoryFrame
         */
        private BreadCollection breadFactory;

        public BreadFactoryFrame() {
                initComponents();
                this.breadFactory = new BreadCollection();
                this.breadFactory.initAmountOfFlour();
        }

        private void getNumOfLoaves() {
                this.breadFactory.getBread(0).setNoOfLoaves(Integer.parseInt(plain_input.getText()));
                this.breadFactory.getBread(1).setNoOfLoaves(Integer.parseInt(wholemeal_input.getText()));
                this.breadFactory.getBread(2).setNoOfLoaves(Integer.parseInt(raisin_input.getText()));
                this.breadFactory.getBread(3).setNoOfLoaves(Integer.parseInt(banana_input.getText()));
                this.breadFactory.getBread(4).setNoOfLoaves(Integer.parseInt(corn_input.getText()));
        }

        public static String spaces(int num) {
                String result = "";
                for (int i = 0; i < num; i++) {
                        result += " ";
                }
                return result;
        }

        private void displayCosts() {
                String msg = "Type\tNumber of Loaves\tTotal Cost\n";
                msg += "====\t================\t=============\n";

                for (int i = 0; i < breadFactory.getNumOfBreads(); i++) {
                        Bread b = breadFactory.getBread(i);
                        double costs = b.getNoOfLoaves() * b.getAmtOfFlour() * this.breadFactory.getCostOfFlour();
                        msg += b.getName() + "\t" + b.getNoOfLoaves() + "\t\t$" + costs + "\n";
                }
                output_text_field.setText(msg);
        }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jLabel1 = new javax.swing.JLabel();
                flour_cost_input = new javax.swing.JTextField();
                jLabel2 = new javax.swing.JLabel();
                jLabel3 = new javax.swing.JLabel();
                plain_input = new javax.swing.JTextField();
                jLabel4 = new javax.swing.JLabel();
                wholemeal_input = new javax.swing.JTextField();
                jLabel5 = new javax.swing.JLabel();
                raisin_input = new javax.swing.JTextField();
                jLabel6 = new javax.swing.JLabel();
                banana_input = new javax.swing.JTextField();
                jLabel7 = new javax.swing.JLabel();
                corn_input = new javax.swing.JTextField();
                calculate_button = new javax.swing.JButton();
                save_to_file_btn = new javax.swing.JButton();
                retrieve_button = new javax.swing.JButton();
                clear_btn = new javax.swing.JButton();
                jScrollPane1 = new javax.swing.JScrollPane();
                output_text_field = new javax.swing.JTextArea();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                jLabel1.setText("Cost of Flour ( $ / gram )");

                flour_cost_input.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                flour_cost_inputActionPerformed(evt);
                        }
                });

                jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
                jLabel2.setText("Number of Loaves");

                jLabel3.setText("Plain Loaf");

                plain_input.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                plain_inputActionPerformed(evt);
                        }
                });

                jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                jLabel4.setText("Wholemeal Loaf");

                wholemeal_input.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                wholemeal_inputActionPerformed(evt);
                        }
                });

                jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                jLabel5.setText("Raisin Loaf");

                raisin_input.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                raisin_inputActionPerformed(evt);
                        }
                });

                jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                jLabel6.setText("Banana Loaf");

                banana_input.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                banana_inputActionPerformed(evt);
                        }
                });

                jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                jLabel7.setText("Corn Loaf");

                corn_input.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                corn_inputActionPerformed(evt);
                        }
                });

                calculate_button.setText("Calculate");
                calculate_button.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                calculate_buttonActionPerformed(evt);
                        }
                });

                save_to_file_btn.setText("Save to File");
                save_to_file_btn.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                save_to_file_btnActionPerformed(evt);
                        }
                });

                retrieve_button.setText("Retriecve from File");

                clear_btn.setText("Clear");
                clear_btn.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                clear_btnActionPerformed(evt);
                        }
                });

                output_text_field.setColumns(20);
                output_text_field.setRows(5);
                jScrollPane1.setViewportView(output_text_field);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addGap(39, 39, 39)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                false)
                                                                                .addComponent(jScrollPane1)
                                                                                .addGroup(layout.createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                false)
                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                .addComponent(save_to_file_btn)
                                                                                                                .addPreferredGap(
                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                                .addComponent(retrieve_button)
                                                                                                                .addPreferredGap(
                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                                .addComponent(clear_btn))
                                                                                                .addComponent(jLabel2)
                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                .addComponent(jLabel1)
                                                                                                                .addGap(18, 18, 18)
                                                                                                                .addComponent(flour_cost_input,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                80,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                                                false)
                                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                                .addComponent(jLabel3)
                                                                                                                                                .addPreferredGap(
                                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                                .addComponent(plain_input,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                80,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                                .addComponent(jLabel7)
                                                                                                                                                .addPreferredGap(
                                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                                .addComponent(corn_input,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                80,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                                .addComponent(jLabel6)
                                                                                                                                                .addPreferredGap(
                                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                                .addComponent(banana_input,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                80,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                                .addComponent(jLabel5)
                                                                                                                                                .addPreferredGap(
                                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                                .addComponent(raisin_input,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                80,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                                .addComponent(jLabel4)
                                                                                                                                                .addGap(18, 18, 18)
                                                                                                                                                .addComponent(wholemeal_input,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                80,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                                                                .addGap(28, 28, 28)
                                                                                                                .addComponent(calculate_button,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                Short.MAX_VALUE))))
                                                                .addContainerGap(36, Short.MAX_VALUE)));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addGap(41, 41, 41)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel1)
                                                                                .addComponent(flour_cost_input,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jLabel2)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel3)
                                                                                .addComponent(plain_input,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel4)
                                                                                .addComponent(wholemeal_input,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel5)
                                                                                .addComponent(raisin_input,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel6)
                                                                                .addComponent(banana_input,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel7)
                                                                                .addComponent(corn_input,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(calculate_button))
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jScrollPane1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                180,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(26, 26, 26)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(save_to_file_btn)
                                                                                .addComponent(retrieve_button)
                                                                                .addComponent(clear_btn))
                                                                .addContainerGap(37, Short.MAX_VALUE)));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void retrieve_buttonActionPerformed(java.awt.event.ActionEvent evt) {
                // TODO add your handling code here:
                // load the breadFactory.dat serialized file
                try {
                        FileInputStream fileIn = new FileInputStream("src/Practical6/breadFactory.dat");
                        ObjectInputStream in = new ObjectInputStream(fileIn);
                        this.breadFactory = (BreadCollection) in.readObject();
                        in.close();
                        fileIn.close();
                } catch (IOException i) {
                        i.printStackTrace();
                        return;
                } catch (ClassNotFoundException c) {
                        System.out.println("BreadFactory class not found");
                        c.printStackTrace();
                        return;
                }
        }

        private void flour_cost_inputActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_flour_cost_inputActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_flour_cost_inputActionPerformed

        private void plain_inputActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_plain_inputActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_plain_inputActionPerformed

        private void raisin_inputActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_raisin_inputActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_raisin_inputActionPerformed

        private void wholemeal_inputActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_wholemeal_inputActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_wholemeal_inputActionPerformed

        private void banana_inputActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_banana_inputActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_banana_inputActionPerformed

        private void corn_inputActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_corn_inputActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_corn_inputActionPerformed

        private void calculate_buttonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_calculate_buttonActionPerformed
                // TODO add your handling code here:
                this.breadFactory.setCostOfFlour(Double.parseDouble(flour_cost_input.getText()));
                getNumOfLoaves();
                displayCosts();
        }// GEN-LAST:event_calculate_buttonActionPerformed

        private void clear_btnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_clear_btnActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_clear_btnActionPerformed

        private void save_to_file_btnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_save_to_file_btnActionPerformed
                /*
                 * 
                 * save to file in this format:
                 * 0.05
                 * Plain, 100
                 * Wholemeal, 200
                 * Raisin,300
                 * Banana, 400
                 * Corn, 500
                 */

                try {
                        FileWriter fw = new FileWriter("src/Practical6/Q3/bread.txt");
                        BufferedWriter bw = new BufferedWriter(fw);
                        PrintWriter pw = new PrintWriter(bw);

                        pw.println(flour_cost_input.getText());
                        pw.println("Plain, " + plain_input.getText());
                        pw.println("Wholemeal, " + wholemeal_input.getText());
                        pw.println("Raisin, " + raisin_input.getText());
                        pw.println("Banana, " + banana_input.getText());
                        pw.println("Corn, " + corn_input.getText());

                        pw.close();
                        bw.close();
                        fw.close();

                        // serialise the breadFactory object to a file called breadFactory.dat
                        FileOutputStream fileOut = new FileOutputStream("src/Practical6/Q3/breadFactory.dat");
                        ObjectOutputStream out = new ObjectOutputStream(fileOut);
                        out.writeObject(this.breadFactory);
                        out.close();
                        fileOut.close();

                } catch (IOException e) {
                        e.printStackTrace();
                }
        }// GEN-LAST:event_save_to_file_btnActionPerformed

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {

                /* Set the Nimbus look and feel */
                // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
                // (optional) ">
                /*
                 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
                 * look and feel.
                 * For details see
                 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                                        .getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(BreadFactoryFrame.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(BreadFactoryFrame.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(BreadFactoryFrame.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(BreadFactoryFrame.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                }
                // </editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new BreadFactoryFrame().setVisible(true);
                        }
                });
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JTextField banana_input;
        private javax.swing.JButton calculate_button;
        private javax.swing.JButton clear_btn;
        private javax.swing.JTextField corn_input;
        private javax.swing.JTextField flour_cost_input;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JTextArea output_text_field;
        private javax.swing.JTextField plain_input;
        private javax.swing.JTextField raisin_input;
        private javax.swing.JButton retrieve_button;
        private javax.swing.JButton save_to_file_btn;
        private javax.swing.JTextField wholemeal_input;
        // End of variables declaration//GEN-END:variables
}
