/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Practical5;

import javax.swing.JOptionPane;

/**
 *
 * @author elliott
 */
public class hotel extends javax.swing.JFrame {

	/**
	 * Creates new form hotel
	 */
	public hotel() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                buttonGroup1 = new javax.swing.ButtonGroup();
                buttonGroup2 = new javax.swing.ButtonGroup();
                buttonGroup3 = new javax.swing.ButtonGroup();
                jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
                jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
                buttonGroup4 = new javax.swing.ButtonGroup();
                buttonGroup5 = new javax.swing.ButtonGroup();
                buttonGroup6 = new javax.swing.ButtonGroup();
                buttonGroup7 = new javax.swing.ButtonGroup();
                buttonGroup8 = new javax.swing.ButtonGroup();
                buttonGroup9 = new javax.swing.ButtonGroup();
                buttonGroup10 = new javax.swing.ButtonGroup();
                buttonGroup11 = new javax.swing.ButtonGroup();
                buttonGroup12 = new javax.swing.ButtonGroup();
                buttonGroup13 = new javax.swing.ButtonGroup();
                jLabel1 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                guestTF = new javax.swing.JTextField();
                jCheckBox1 = new javax.swing.JCheckBox();
                jLabel3 = new javax.swing.JLabel();
                roomsCombo = new javax.swing.JComboBox<>();
                jLabel4 = new javax.swing.JLabel();
                nightsCombo = new javax.swing.JComboBox<>();
                jLabel5 = new javax.swing.JLabel();
                jRadioButton1 = new javax.swing.JRadioButton();
                jRadioButton2 = new javax.swing.JRadioButton();
                jRadioButton3 = new javax.swing.JRadioButton();
                submitBtn = new javax.swing.JButton();
                jScrollPane2 = new javax.swing.JScrollPane();
                jTextArea2 = new javax.swing.JTextArea();

                jCheckBoxMenuItem1.setSelected(true);
                jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

                jCheckBoxMenuItem2.setSelected(true);
                jCheckBoxMenuItem2.setText("jCheckBoxMenuItem2");

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
                jLabel1.setText("Hotel Booking");

                jLabel2.setText("Guest name");

                guestTF.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                guestTFActionPerformed(evt);
                        }
                });

                jCheckBox1.setText("First time guest ( 15% off )");
                jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jCheckBox1ActionPerformed(evt);
                        }
                });

                jLabel3.setText("Rooms");

                roomsCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
                roomsCombo.addHierarchyListener(new java.awt.event.HierarchyListener() {
                        public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                                roomsComboHierarchyChanged(evt);
                        }
                });
                roomsCombo.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                roomsComboActionPerformed(evt);
                        }
                });

                jLabel4.setText("Nights");

                nightsCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
                nightsCombo.addHierarchyListener(new java.awt.event.HierarchyListener() {
                        public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                                nightsComboHierarchyChanged(evt);
                        }
                });
                nightsCombo.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                nightsComboActionPerformed(evt);
                        }
                });

                jLabel5.setText("Room Type:");

                buttonGroup1.add(jRadioButton1);
                jRadioButton1.setText("Single");
                jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jRadioButton1ActionPerformed(evt);
                        }
                });

                buttonGroup1.add(jRadioButton2);
                jRadioButton2.setText("Double");

                buttonGroup1.add(jRadioButton3);
                jRadioButton3.setText("Twin");

                submitBtn.setText("Submit");
                submitBtn.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                submitBtnActionPerformed(evt);
                        }
                });

                jTextArea2.setEditable(false);
                jTextArea2.setColumns(20);
                jTextArea2.setRows(5);
                jScrollPane2.setViewportView(jTextArea2);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(81, 81, 81)
                                                .addComponent(jLabel2)
                                                .addGap(29, 29, 29)
                                                .addComponent(guestTF, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(222, 222, 222)
                                                .addComponent(jLabel1)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jCheckBox1)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addGap(18, 18, 18)
                                                .addComponent(roomsCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(39, 39, 39)
                                                .addComponent(jLabel4)
                                                .addGap(18, 18, 18)
                                                .addComponent(nightsCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(submitBtn)
                                        .addComponent(jLabel5)
                                        .addComponent(jRadioButton2)
                                        .addComponent(jRadioButton3)
                                        .addComponent(jRadioButton1))
                                .addGap(58, 58, 58))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(guestTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jRadioButton1)
                                                .addGap(4, 4, 4)
                                                .addComponent(jRadioButton2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jRadioButton3))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(38, 38, 38)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel3)
                                                        .addComponent(roomsCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel4)
                                                        .addComponent(nightsCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(submitBtn)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(54, Short.MAX_VALUE))
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void guestTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guestTFActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_guestTFActionPerformed

        private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_jCheckBox1ActionPerformed

        private void roomsComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomsComboActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_roomsComboActionPerformed

        private void roomsComboHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_roomsComboHierarchyChanged
                // TODO add your handling code here:
        }//GEN-LAST:event_roomsComboHierarchyChanged

        private void nightsComboHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_nightsComboHierarchyChanged
                // TODO add your handling code here:
        }//GEN-LAST:event_nightsComboHierarchyChanged

        private void nightsComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nightsComboActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_nightsComboActionPerformed

        private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_jRadioButton1ActionPerformed

        private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
                // TODO add your handling code here:
		String name = guestTF.getText();
		if (name.length() == 0) {
			JOptionPane.showMessageDialog(null, "Please enter your name", "Error", JOptionPane.ERROR_MESSAGE);
		}
        }//GEN-LAST:event_submitBtnActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(hotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(hotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(hotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(hotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new hotel().setVisible(true);
			}
		});
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.ButtonGroup buttonGroup1;
        private javax.swing.ButtonGroup buttonGroup10;
        private javax.swing.ButtonGroup buttonGroup11;
        private javax.swing.ButtonGroup buttonGroup12;
        private javax.swing.ButtonGroup buttonGroup13;
        private javax.swing.ButtonGroup buttonGroup2;
        private javax.swing.ButtonGroup buttonGroup3;
        private javax.swing.ButtonGroup buttonGroup4;
        private javax.swing.ButtonGroup buttonGroup5;
        private javax.swing.ButtonGroup buttonGroup6;
        private javax.swing.ButtonGroup buttonGroup7;
        private javax.swing.ButtonGroup buttonGroup8;
        private javax.swing.ButtonGroup buttonGroup9;
        private javax.swing.JTextField guestTF;
        private javax.swing.JCheckBox jCheckBox1;
        private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
        private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JRadioButton jRadioButton1;
        private javax.swing.JRadioButton jRadioButton2;
        private javax.swing.JRadioButton jRadioButton3;
        private javax.swing.JScrollPane jScrollPane2;
        private javax.swing.JTextArea jTextArea2;
        private javax.swing.JComboBox<String> nightsCombo;
        private javax.swing.JComboBox<String> roomsCombo;
        private javax.swing.JButton submitBtn;
        // End of variables declaration//GEN-END:variables
}

